name: Build and Push Docker Images

on:
  push:
    branches:
      - main  # Dies löst den Workflow aus, wenn in den main-Branch gemergt wird

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # Der Workflow läuft auf einem Ubuntu-VM

    steps:
      # Schritt 1: Repository checkouten
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Schritt 2: Docker Hub Login
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Schritt 3: Frontend-Image bauen und pushen
      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend  # Kontext für das Frontend
          file: ./frontend/Dockerfile  # Dockerfile für Frontend
          push: true  # Image zu Docker Hub pushen
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest

      # Schritt 4: Backend-Image bauen und pushen
      - name: Build and Push Backend Image
        uses: docker/build-push-action@v5
        with:
          context: ./backend  # Kontext für das Backend
          file: ./backend/Dockerfile  # Dockerfile für Backend
          push: true  # Image zu Docker Hub pushen
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest
